spring.application.name=inte5A
# MYSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# Propiedades
spring.jpa.generate-ddl=true
# Crear la estructura de entidades
spring.jpa.hibernate.ddl-auto=create-drop
# Ver querys
spring.jpa.show-sql=true

# JWT Config
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Email Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gestionbienes.noreply@gmail.com
spring.mail.password=qjxvysixmysogpes
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

# Cloudinary Config
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Configuración CORS para producción
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

